version: '3'
services:
  db-zotero-mysql:
    image: 'mysql:5.7'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=zotero
    volumes:
      - './config/mysql/conf.d:/etc/mysql/conf.d'
  db-zotero-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.3.0'
    environment:
      - cluster.name=zotero
      - xpack.security.enabled=false
  db-zotero-redis:
    image: 'redis:5.0'
  db-zotero-memcached:
    image: 'memcached:1.5'
    restart: always
  db-zotero-localstack:
    image: atlassianlabs/localstack
    environment:
      - 'SERVICES=sns,sqs,apigateway'
  db-zotero-minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=zotero
      - MINIO_SECRET_KEY=zoterodocker
    command: server /data
  app-zotero:
    image: app-zotero
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
      - '8081:81'
      - '8082:8082'
    volumes:
      - './config/config.inc.php:/var/www/zotero/include/config/config.inc.php:ro'
      - './config/dbconnect.inc.php:/var/www/zotero/include/config/dbconnect.inc.php:ro'
      - './config/default.js:/var/www/stream-server/config/default.js:ro'
      - './config/dataserver-scripts/create-user.sh:/var/www/zotero/admin/create-user.sh:ro'
      - './config/dataserver-scripts/list-user.sh:/var/www/zotero/admin/list-user.sh:ro'
      - './config/dataserver-scripts/www.sql:/var/www/zotero/misc/www.sql:ro'
      - './config/dataserver-scripts/init-mysql.sh:/var/www/zotero/misc/init-mysql.sh:ro'
      - './config/dataserver-scripts/getUserID.sh:/var/www/zotero/admin/getUserID.sh:ro'
      - './config/dataserver-scripts/getLibraryID.sh:/var/www/zotero/admin/getLibraryID.sh:ro'
      - './config/dataserver-scripts/getID.sh:/var/www/zotero/admin/getID.sh:ro'
      - './config/dataserver-scripts/delete-user.sh:/var/www/zotero/admin/delete-user.sh:ro'
      - './config/dataserver-scripts/create-group.sh:/var/www/zotero/admin/create-group.sh:ro'
      - './config/wait-for-it.sh:/wait-for-it.sh:ro'
      - './config/reinit.sh:/var/www/zotero/admin/reinit.sh:ro'
    environment:
      - RUN_USER=www-data
      - RUN_GROUP=www-data
    depends_on:
      - db-zotero-mysql
      - db-zotero-elasticsearch
      - db-zotero-memcached
      - db-zotero-localstack
      - db-zotero-minio
      - db-zotero-redis
    links:
      - 'db-zotero-mysql:mysql'
      - 'db-zotero-elasticsearch:elasticsearch'
      - 'db-zotero-redis:redis'
      - 'db-zotero-memcached:memcached'
      - 'db-zotero-localstack:localstack'
      - 'db-zotero-minio:minio'
    command: 
      - /wait-for-it.sh db-zotero-redis:6379 -- /entrypoint.sh
      - /var/www/zotero/admin/reinit.sh
  app-zotero-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8083:80'
    environment:
      - PMA_HOST=mysql
    links:
      - 'db-zotero-mysql:mysql'
